---
- name: Task 2
  hosts: CSR1kv
  gather_facts: false
  connection: local
  tasks:
  - name: DISPLAYING VERSION NUMBER
    ios_command:
      commands:
      - show version

  - name: DISPLAYING INTERFACES
    ios_command:
      commands:
      - show version
  - name: CLEARING COUNTERS
    ios_command:
      commands:
      - clear counters g0/1
      - y