---
- name: Task 2
  hosts: CSR1kv
  gather_facts: false
  connection: local
  tasks:
  - name: DISPLAYING VERSION NUMBER
    ios_command:
      commands:
      - show version

  - name: DISPLAYING INTERFACES
    ios_command:
      commands:
      - show interfaces

  - name: CLEARING COUNTERS
    ios_command:
      commands:
      - command: clear counters
        prompt: Clear "show interface" counters on all interfaces [confirm]
        answer: y


        